@baseUrl=http://localhost:5000/recipeIngredients

### CREATE NEW RECIPE INGREDIENT
POST {{baseUrl}}/createRecipeIngredient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5ZThiNjZmMzc5Y2VhODJjMzk3ODUiLCJpYXQiOjE3MjY5Mzc0NzIsImV4cCI6MTcyNjk0MTA3Mn0.dG6kL7G2s9Vu0i3D-cwJV27a0jRZrvAg0kvRDqLzNLs

{
    "recipeId": "66eddb6dd83658245ea06df1",
    "ingredientId": "66eb43ae558e722c226da75c",
    "measurementUnit": "g",
    "phaseId": null,
    "quantity": "10",
    "additionalInfos": "scioto al microonde"
}

### UPDATE RECIPE INGREDIENT
PUT {{baseUrl}}/66eef9d0f10b621c1cca8840/editRecipeIngredient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5ZThiNjZmMzc5Y2VhODJjMzk3ODUiLCJpYXQiOjE3MjY5Mzc0NzIsImV4cCI6MTcyNjk0MTA3Mn0.dG6kL7G2s9Vu0i3D-cwJV27a0jRZrvAg0kvRDqLzNLs

{
    "recipeId": "66eddb6dd83658245ea06df1",
    "ingredientId": "66eb43ae558e722c226da75c",
    "measurementUnit": "g",
    "phaseId": null,
    "quantity": "10",
    "additionalInfos": "sciolto al microonde"
}

### DELETE RECIPE INGREDIENT
DELETE {{baseUrl}}/66eef9d0f10b621c1cca8840/deleteRecipeIngredient
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5ZThiNjZmMzc5Y2VhODJjMzk3ODUiLCJpYXQiOjE3MjY5Mzc0NzIsImV4cCI6MTcyNjk0MTA3Mn0.dG6kL7G2s9Vu0i3D-cwJV27a0jRZrvAg0kvRDqLzNLs
