@baseUrl=http://localhost:5000/recipe

### GET PUBLIC INGREDIENTS
GET {{baseUrl}}/public?searchString=ac

### GET ALL INGREDIENTS
GET {{baseUrl}}?searchString=ac
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5ZThiNjZmMzc5Y2VhODJjMzk3ODUiLCJpYXQiOjE3MjY3Njg5NTAsImV4cCI6MTcyNjc3MjU1MH0.BjazopgYqVluvLfDA0RsN3jNXO81f5RulTbIQjhL-uQ

### GET PRIVATE INGREDIENTS
GET {{baseUrl}}/private
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5ZThiNjZmMzc5Y2VhODJjMzk3ODUiLCJpYXQiOjE3MjY3Njg5NTAsImV4cCI6MTcyNjc3MjU1MH0.BjazopgYqVluvLfDA0RsN3jNXO81f5RulTbIQjhL-uQ

### CREATE RECIPE HEADER
POST {{baseUrl}}/createRecipeHeader
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5ZThiNjZmMzc5Y2VhODJjMzk3ODUiLCJpYXQiOjE3MjY4NjQwMDgsImV4cCI6MTcyNjg2NzYwOH0.wjU37itREVVmIKA2mCF6cibHynWBjTn933EEyQeLRCk

{
    "userId": "66e9e8b66f379cea82c39785",
    "tagsIds": [],
    "title": "Ricetta Test 1",
    "description": "Descrizione Ricetta Test 1",
    "portions": "4",
    "preparationTime": "10",
    "recipeImageUrl": "https://picsum.photos/200/300",
    "recipeVideoUrl": "",
    "privateRecipe": false,
    "phases": [],
    "recipeIngredients": []
}

### SAVE RECIPE
POST {{baseUrl}}/saveRecipe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5ZThiNjZmMzc5Y2VhODJjMzk3ODUiLCJpYXQiOjE3MjcwMzg5MDIsImV4cCI6MTcyNzA0MjUwMn0.fEFh5l0j07P4TrbSYPa7VjcF3iNxJoJ_jSvCeKLipW0

{
    "userId": "66e9e8b66f379cea82c39785",
    "tagsIds": [],
    "title": "Ricetta Test 2",
    "description": "Descrizione Ricetta Test 2",
    "portions": "8",
    "preparationTime": "20",
    "recipeImageUrl": "https://picsum.photos/200/300",
    "recipeVideoUrl": "",
    "privateRecipe": false,
    "phases": [
        {
            "phaseIngredients": [
                {
                    "ingredientId": "66eb43ae558e722c226da775",
                    "measurementUnit": "g",
                    "phaseId": null,
                    "quantity": "100",
                    "additionalInfos": "fave di stocazzo"
                },
                {
                    "ingredientId": "66eb43ae558e722c226da77c",
                    "measurementUnit": "g",
                    "phaseId": null,
                    "quantity": "50",
                    "additionalInfos": "non so cosa sia"
                }
            ],
            "phaseNumber": "1",
            "description": "fase 1",
            "phaseImageUrl": "https://picsum.photos/200/300"
        },
        {
            "phaseIngredients": [
                {
                    "ingredientId": "66eb43ae558e722c226da784",
                    "measurementUnit": "g",
                    "phaseId": null,
                    "quantity": "30",
                    "additionalInfos": "bianchissimo"
                },
                {
                    "ingredientId": "66eb43ae558e722c226da78c",
                    "measurementUnit": "g",
                    "phaseId": null,
                    "quantity": "20",
                    "additionalInfos": "sniff"
                }
            ],
            "phaseNumber": "2",
            "description": "fase 2",
            "phaseImageUrl": "https://picsum.photos/200/300"
        }
    ],
    "recipeIngredients": [
        {
            "ingredientId": "66eb43ae558e722c226da767",
            "measurementUnit": "g",
            "phaseId": null,
            "quantity": "10",
            "additionalInfos": "battuta al coltello"
        },
        {
            "ingredientId": "66eb43ae558e722c226da772",
            "measurementUnit": "g",
            "phaseId": null,
            "quantity": "10",
            "additionalInfos": "puliti bene"
        }
    ]
}

### UPDATE RECIPE
PUT {{baseUrl}}/66eddb6dd83658245ea06df1/editRecipe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5ZThiNjZmMzc5Y2VhODJjMzk3ODUiLCJpYXQiOjE3MjY4NjQwMDgsImV4cCI6MTcyNjg2NzYwOH0.wjU37itREVVmIKA2mCF6cibHynWBjTn933EEyQeLRCk

{
    "phases": ["66eddbacd83658245ea06df4","66eddbb7d83658245ea06df7","66eddbbdd83658245ea06dfa"],
    "recipeIngredients":["66ede1a1738fc3ce45bb9fd6"]
}

### DELETE RECIPE
DELETE {{baseUrl}}/66f0865b1fb087d1337cf55f/deleteRecipe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmU5ZThiNjZmMzc5Y2VhODJjMzk3ODUiLCJpYXQiOjE3MjcwMzg5MDIsImV4cCI6MTcyNzA0MjUwMn0.fEFh5l0j07P4TrbSYPa7VjcF3iNxJoJ_jSvCeKLipW0
